# for local development
version: "3.7"
services:
  cli:
    build:
      context: .
      target: "develop-stage"
    volumes:
      - ".:/app"
    tty: true
    networks:
      - testsuite_backend

networks:
  testsuite_backend:
     external:
      name: testsuite_backend_external
