version: "3.7"

services:
  cli:
    # image: testsoothe/cli
    build:
      context: .
      target: "develop-stage"
    environment:
      DEBUGGING_PORT: ${TEST_DEBUGGING_PORT}
    volumes:
      - .:/app
    ports:
      - ${TEST_DEBUGGING_PORT}:${TEST_DEBUGGING_PORT}
    tty: true
    stdin_open: true
    networks:
      - testsoothe

networks:
  testsoothe:
     external:
      name: testsoothe
